import { Policy, PublicationError } from "./core.js";
export class NotionClient { static readonly version="2025-09-03"; static readonly marker="Publisher-owned Symphony coordination surface v1"; static readonly pendingMarker=`${NotionClient.marker}; bootstrap=pending`; static readonly completeMarker=`${NotionClient.marker}; bootstrap=complete`; constructor(private readonly token:string,private readonly fetcher=globalThis.fetch){}
 async request(method:string,path:string,body?:unknown):Promise<any>{const r=await this.fetcher("https://api.notion.com/v1"+path,{method,headers:{Authorization:`Bearer ${this.token}`,"Notion-Version":NotionClient.version,"Content-Type":"application/json"},body:body===undefined?undefined:JSON.stringify(body)}); if(!r.ok){if(r.status===401)throw new PublicationError("authentication failure: NOTION_TOKEN was rejected");if(r.status===403||r.status===404)throw new PublicationError("target inaccessible to the integration: share the parent page and grant read/insert access");throw new PublicationError(`provider/API failure (${r.status}): ${(await r.text()).slice(0,300)}`);}return r.json();}
 async ensureSurface(parentId:string,p:Policy):Promise<string>{let cursor:string|undefined;do{const q=await this.request("GET",`/blocks/${parentId}/children?page_size=100${cursor?`&start_cursor=${encodeURIComponent(cursor)}`:""}`);for(const b of q.results??[]){if(b.type!=="child_database"||b.child_database?.title!==p.surfaceName)continue;const db=await this.request("GET",`/databases/${b.id}`);const desc=(db.description??[]).map((x:any)=>x.plain_text??"").join(" ");const owned=desc.includes(NotionClient.marker);if(!owned)throw new PublicationError("incompatible schema: a same-named database exists but is not publisher-owned");const ds=db.data_sources?.[0]?.id;if(!ds)throw new PublicationError("incompatible schema: coordination surface has no data source");const schema=await this.request("GET",`/data_sources/${ds}`);if(desc.includes(NotionClient.completeMarker)){this.validateSchema(schema,p,ds);return ds;}await this.completeBootstrap(schema,ds,p);await this.markComplete(db.id);return ds;}cursor=q.has_more?q.next_cursor:undefined;}while(cursor);return this.bootstrap(parentId,p);}
 private async bootstrap(parentId:string,p:Policy):Promise<string>{const schema:any={[p.identifier]:{rich_text:{}},[p.title]:{title:{}},[p.state]:{select:{options:p.bootstrapStates.map(name=>({name}))}},[p.priority]:{number:{}},[p.labels]:{multi_select:{}},[p.description]:{rich_text:{}},[p.source]:{url:{}}};const db=await this.request("POST","/databases",{parent:{type:"page_id",page_id:parentId},title:[{text:{content:p.surfaceName}}],description:[{text:{content:NotionClient.pendingMarker}}],initial_data_source:{properties:schema}});const full=await this.request("GET",`/databases/${db.id}`);const ds=full.data_sources?.[0]?.id;if(!ds)throw new PublicationError("provider/API failure: created surface did not expose its data source");await this.request("PATCH",`/data_sources/${ds}`,{properties:{[p.blockedBy]:{relation:{data_source_id:ds,single_property:{}}}}});await this.markComplete(db.id);return ds;}
 private markComplete(databaseId:string){return this.request("PATCH",`/databases/${databaseId}`,{description:[{text:{content:NotionClient.completeMarker}}]});}
 validateSchema(data:any,p:Policy,ds?:string):void{const expected:any={[p.identifier]:"rich_text",[p.title]:"title",[p.state]:"select",[p.priority]:"number",[p.labels]:"multi_select",[p.blockedBy]:"relation",[p.description]:"rich_text",[p.source]:"url"};for(const [name,type] of Object.entries(expected))if(data.properties?.[name]?.type!==type)throw new PublicationError(`incompatible schema: property ${name} must be ${type}`);const relation=data.properties[p.blockedBy].relation??{};if(ds&&(relation.data_source_id!==ds||(!relation.single_property&&!relation.dual_property)))throw new PublicationError(`incompatible schema: property ${p.blockedBy} must be a self-relation`);}
 private async completeBootstrap(data:any,ds:string,p:Policy){const definitions:Record<string,any>={[p.identifier]:{rich_text:{}},[p.title]:{title:{}},[p.state]:{select:{options:p.bootstrapStates.map(name=>({name}))}},[p.priority]:{number:{}},[p.labels]:{multi_select:{}},[p.blockedBy]:{relation:{data_source_id:ds,single_property:{}}},[p.description]:{rich_text:{}},[p.source]:{url:{}}};const missing:any={};for(const [name,definition] of Object.entries(definitions)){const existing=data.properties?.[name];if(!existing){missing[name]=definition;continue;}const expected=name===p.blockedBy?"relation":Object.keys(definition)[0];if(existing.type!==expected)throw new PublicationError(`incompatible schema: property ${name} has the wrong type`);if(name===p.blockedBy){const relation=existing.relation??{};if(relation.data_source_id!==ds||(!relation.single_property&&!relation.dual_property))throw new PublicationError(`incompatible schema: property ${p.blockedBy} must be a self-relation`);}}if(Object.keys(missing).length)await this.request("PATCH",`/data_sources/${ds}`,{properties:missing});}
 async duplicate(ds:string,p:Policy,id:string){const q=await this.request("POST",`/data_sources/${ds}/query`,{filter:{property:p.identifier,rich_text:{equals:id}}});return (q.results??[]).length>0;}
 async findPublication(ds:string,p:Policy,id:string):Promise<{pageId:string;url?:string;complete:boolean}|null>{const q=await this.request("POST",`/data_sources/${ds}/query`,{filter:{property:p.identifier,rich_text:{equals:id}}});const row=q.results?.[0];if(!row)return null;const children=await this.request("GET",`/blocks/${row.id}/children?page_size=100`);const complete=(children.results??[]).some((b:any)=>b.type==="heading_1"&&b.heading_1?.rich_text?.some((r:any)=>r.plain_text==="Workpad"||r.text?.content==="Workpad"));return {pageId:row.id,url:row.url,complete};}
 createTask(ds:string,properties:Record<string,unknown>){return this.request("POST","/pages",{parent:{type:"data_source_id",data_source_id:ds},properties});}
 async appendBlocks(pageId:string,blocks:Record<string,unknown>[]){for(let i=0;i<blocks.length;i+=50)await this.request("PATCH",`/blocks/${pageId}/children`,{children:blocks.slice(i,i+50)});}
 async repairIncomplete(pageId:string,blocks:Record<string,unknown>[]){const children=await this.request("GET",`/blocks/${pageId}/children?page_size=100`);for(const block of children.results??[])await this.request("PATCH",`/blocks/${block.id}`,{archived:true});await this.appendBlocks(pageId,blocks);}
 archive(pageId:string){return this.request("PATCH",`/pages/${pageId}`,{archived:true});}
}
