import test from "node:test";import assert from "node:assert/strict";import { NotionClient } from "../src/notion.js";import { DEFAULT_POLICY, buildPageBlocks, PublicationError } from "../src/core.js";
class FakeClient extends NotionClient { responses:any[]; calls:any[]=[]; constructor(responses:any[]){super("token");this.responses=responses;} override async request(method:string,path:string,body?:unknown){this.calls.push({method,path,body});const result=this.responses.shift();if(result instanceof Error)throw result;return result;}}
test("incomplete identifier publication is repaired instead of treated as duplicate",async()=>{const c=new FakeClient([{results:[{id:"page",url:"url"}]},{results:[{id:"old-block"}]},{results:[{id:"old-block"}]},{ok:true},{ok:true}]);const found=await c.findPublication("ds",DEFAULT_POLICY,"PLAN-X");assert.deepEqual(found,{pageId:"page",url:"url",complete:false});await c.repairIncomplete("page",buildPageBlocks(DEFAULT_POLICY,"plan"));assert.equal(c.calls[3].method,"PATCH");assert.deepEqual(c.calls[3].body,{archived:true});assert.equal(c.calls.at(-1)?.path,"/blocks/page/children");});
test("complete identifier publication remains a duplicate",async()=>{const c=new FakeClient([{results:[{id:"page"}]},{results:[{type:"heading_1",heading_1:{rich_text:[{plain_text:"Workpad"}]}}]}]);const found=await c.findPublication("ds",DEFAULT_POLICY,"PLAN-X");assert.equal(found?.complete,true);});
test("completion and repair traverse all child pages",async()=>{const filler=Array.from({length:100},(_,i)=>({id:`old-${i}`}));const c=new FakeClient([{results:[{id:"page"}]},{results:filler,has_more:true,next_cursor:"next"},{results:[{id:"workpad",type:"heading_1",heading_1:{rich_text:[{plain_text:"Workpad"}]}}],has_more:false},{results:filler,has_more:true,next_cursor:"next"},{results:[{id:"workpad",type:"heading_1",heading_1:{rich_text:[{plain_text:"Workpad"}]}}],has_more:false},...Array.from({length:101},()=>({ok:true}))]);const found=await c.findPublication("ds",DEFAULT_POLICY,"PLAN-X");assert.equal(found?.complete,true);await c.repairIncomplete("page",buildPageBlocks(DEFAULT_POLICY,"plan"));assert.equal(c.calls.filter(x=>x.method==="PATCH"&&x.path.startsWith("/blocks/old-")).length,100);assert.ok(c.calls.some(x=>x.path==="/blocks/page/children"));});
test("alternate policy heading controls completion detection",async()=>{const policy={...DEFAULT_POLICY,workpadHeading:"Execution Notes"};const c=new FakeClient([{results:[{id:"page"}]},{results:[{type:"heading_1",heading_1:{rich_text:[{plain_text:"Execution Notes"}]}}]}]);const found=await c.findPublication("ds",policy,"PLAN-X");assert.equal(found?.complete,true);});
test("fresh bootstrap establishes pending schema, relation, then complete marker",async()=>{const c=new FakeClient([{results:[],has_more:false},{id:"db"},{data_sources:[{id:"ds"}]},{ok:true},{ok:true}]);assert.equal(await c.ensureSurface("parent",DEFAULT_POLICY),"ds");assert.deepEqual(c.calls.map(x=>x.path),["/blocks/parent/children?page_size=100","/databases","/databases/db","/data_sources/ds","/databases/db"]);assert.equal(c.calls[1].body.description[0].text.content,NotionClient.pendingMarker);assert.equal(c.calls[3].body.properties[DEFAULT_POLICY.blockedBy].relation.data_source_id,"ds");assert.equal(c.calls[4].body.description[0].text.content,NotionClient.completeMarker);});
test("malformed surface-discovery pagination fails before bootstrap",async()=>{const c=new FakeClient([{results:[],has_more:true,next_cursor:null}]);await assert.rejects(c.ensureSurface("parent",DEFAULT_POLICY),/omitted next_cursor/);assert.equal(c.calls.some(x=>x.path==="/databases"),false);});
test("request preserves authentication, access, and provider error categories",async()=>{for(const [status,message] of [[401,"authentication failure"],[403,"target inaccessible"],[500,"provider/API failure"]] as const){const c=new NotionClient("token",async()=>new Response("failure",{status}));await assert.rejects(c.request("GET","/pages/x"),new RegExp(message));}});
