import test from "node:test";import assert from "node:assert/strict";import { NotionClient, PENDING_PUBLICATION_MARKER } from "../src/notion.js";import { DEFAULT_POLICY, buildPageBlocks, PublicationError } from "../src/core.js";
class FakeClient extends NotionClient { responses:any[]; calls:any[]=[]; constructor(responses:any[]){super("token");this.responses=responses;} override async request(method:string,path:string,body?:unknown){this.calls.push({method,path,body});const result=this.responses.shift();if(result instanceof Error)throw result;return result;}}
test("incomplete identifier publication is repaired instead of treated as duplicate",async()=>{const pending={id:"pending",type:"heading_2",heading_2:{rich_text:[{plain_text:PENDING_PUBLICATION_MARKER}]}};const old={id:"old",type:"paragraph"};const c=new FakeClient([{results:[{id:"page",url:"url"}]},{results:[pending]},{results:[pending,old]},{ok:true},{ok:true},{ok:true},{results:[]},{ok:true}]);const found=await c.findPublication("ds",DEFAULT_POLICY,"PLAN-X");assert.deepEqual(found,{pageId:"page",url:"url",complete:false});await c.repairIncomplete("page",buildPageBlocks(DEFAULT_POLICY,"plan"),DEFAULT_POLICY);assert.equal(c.calls[3].path,"/blocks/old");assert.deepEqual(c.calls[3].body,{archived:true});assert.equal(c.calls[4].path,"/blocks/page/children");assert.equal(c.calls[5].path,"/blocks/pending");assert.equal(c.calls[7].path,"/pages/page");});
test("complete identifier publication remains a duplicate",async()=>{const c=new FakeClient([{results:[{id:"page"}]},{results:[{type:"heading_1",heading_1:{rich_text:[{plain_text:"Workpad"}]}}]}]);const found=await c.findPublication("ds",DEFAULT_POLICY,"PLAN-X");assert.equal(found?.complete,true);});
test("completion and repair traverse all child pages",async()=>{const filler=Array.from({length:100},(_,i)=>({id:`old-${i}`}));const c=new FakeClient([{results:[{id:"page"}]},{results:filler,has_more:true,next_cursor:"next"},{results:[{id:"workpad",type:"heading_1",heading_1:{rich_text:[{plain_text:"Workpad"}]}}],has_more:false},{results:filler,has_more:true,next_cursor:"next"},{results:[{id:"workpad",type:"heading_1",heading_1:{rich_text:[{plain_text:"Workpad"}]}}],has_more:false},{results:[]},...Array.from({length:102},()=>({ok:true}))]);const found=await c.findPublication("ds",DEFAULT_POLICY,"PLAN-X");assert.equal(found?.complete,true);await c.repairIncomplete("page",buildPageBlocks(DEFAULT_POLICY,"plan"),DEFAULT_POLICY);assert.equal(c.calls.filter(x=>x.method==="PATCH"&&x.path.startsWith("/blocks/old-")).length,100);assert.ok(c.calls.some(x=>x.path==="/blocks/page/children"));});
test("alternate policy heading controls completion detection",async()=>{const policy={...DEFAULT_POLICY,workpadHeading:"Execution Notes"};const c=new FakeClient([{results:[{id:"page"}]},{results:[{type:"heading_1",heading_1:{rich_text:[{plain_text:"Execution Notes"}]}}]}]);const found=await c.findPublication("ds",policy,"PLAN-X");assert.equal(found?.complete,true);});
test("fresh bootstrap establishes pending schema, relation, then complete marker",async()=>{const c=new FakeClient([{results:[],has_more:false},{id:"db"},{data_sources:[{id:"ds"}]},{ok:true},{ok:true}]);assert.equal(await c.ensureSurface("parent",DEFAULT_POLICY),"ds");assert.deepEqual(c.calls.map(x=>x.path),["/blocks/parent/children?page_size=100","/databases","/databases/db","/data_sources/ds","/databases/db"]);assert.equal(c.calls[1].body.description[0].text.content,NotionClient.pendingMarker);assert.equal(c.calls[3].body.properties[DEFAULT_POLICY.blockedBy].relation.data_source_id,"ds");assert.equal(c.calls[4].body.description[0].text.content,NotionClient.completeMarker);});
test("malformed surface-discovery pagination fails before bootstrap",async()=>{const c=new FakeClient([{results:[],has_more:true,next_cursor:null}]);await assert.rejects(c.ensureSurface("parent",DEFAULT_POLICY),/omitted next_cursor/);assert.equal(c.calls.some(x=>x.path==="/databases"),false);});
test("pending owned surface without a data source resumes through data-source creation",async()=>{const c=new FakeClient([{results:[{type:"child_database",id:"db",child_database:{title:DEFAULT_POLICY.surfaceName}}]},{description:[{plain_text:NotionClient.pendingMarker}],data_sources:[]},{id:"ds"},{ok:true},{ok:true}]);assert.equal(await c.ensureSurface("parent",DEFAULT_POLICY),"ds");assert.equal(c.calls[2].path,"/data_sources");assert.equal(c.calls[3].body.properties[DEFAULT_POLICY.blockedBy].relation.data_source_id,"ds");assert.equal(c.calls[4].body.description[0].text.content,NotionClient.completeMarker);});
test("all same-named surfaces are inspected before selecting one",async()=>{const owned={type:"child_database",id:"owned",child_database:{title:DEFAULT_POLICY.surfaceName}};const unowned={type:"child_database",id:"unowned",child_database:{title:DEFAULT_POLICY.surfaceName}};const c=new FakeClient([{results:[owned,unowned],has_more:false},{description:[{plain_text:NotionClient.completeMarker}],data_sources:[{id:"ds"}]},{description:[],data_sources:[{id:"other"}]}]);await assert.rejects(c.ensureSurface("parent",DEFAULT_POLICY),/not publisher-owned/);assert.equal(c.calls.some(x=>x.path==="/data_sources"),false);});
test("dual Blocked By relation is schema drift",()=>{const relation={data_source_id:"ds",dual_property:{synced_property_name:"Other"}};assert.throws(()=>new NotionClient("token").validateSchema({properties:{[DEFAULT_POLICY.identifier]:{type:"rich_text"},[DEFAULT_POLICY.title]:{type:"title"},[DEFAULT_POLICY.state]:{type:"select"},[DEFAULT_POLICY.priority]:{type:"number"},[DEFAULT_POLICY.labels]:{type:"multi_select"},[DEFAULT_POLICY.blockedBy]:{type:"relation",relation},[DEFAULT_POLICY.description]:{type:"rich_text"},[DEFAULT_POLICY.source]:{type:"url"}}},DEFAULT_POLICY,"ds"),/single_property/);});
test("request preserves authentication, access, and provider error categories",async()=>{for(const [status,message] of [[401,"authentication failure"],[403,"target inaccessible"],[500,"provider/API failure"]] as const){const c=new NotionClient("token",async()=>new Response("failure",{status}));await assert.rejects(c.request("GET","/pages/x"),new RegExp(message));}});
test("appendBlocks batches at the 50-block provider boundary",async()=>{const c=new FakeClient(Array.from({length:2},()=>({ok:true})));await c.appendBlocks("page",Array.from({length:51},()=>({type:"paragraph"})));assert.equal(c.calls.filter(x=>x.path==="/blocks/page/children").length,2);assert.equal(c.calls[0].body.children.length,50);assert.equal(c.calls[1].body.children.length,1);});
test("fetch transport rejection is normalized",async()=>{const c=new NotionClient("token",async()=>{throw new TypeError("network unavailable");});await assert.rejects(c.request("GET","/pages/x"),/provider\/API transport failure/);});
test("successful response with invalid JSON is normalized",async()=>{const c=new NotionClient("token",async()=>new Response("not-json",{status:200}));await assert.rejects(c.request("GET","/pages/x"),/invalid JSON response/);});
test("matching identifier without publisher pending marker remains duplicate",async()=>{const c=new FakeClient([{results:[{id:"page"}]},{results:[{type:"paragraph",paragraph:{rich_text:[{plain_text:"externally managed"}]}}]}]);const found=await c.findPublication("ds",DEFAULT_POLICY,"PLAN-X");assert.equal(found?.complete,true);});
test("task property marker keeps a markerless partial task repairable",async()=>{const c=new FakeClient([{results:[{id:"page",properties:{Description:{rich_text:[{plain_text:PENDING_PUBLICATION_MARKER}]}}}]},{results:[]}]);const found=await c.findPublication("ds",DEFAULT_POLICY,"PLAN-X");assert.equal(found?.complete,false);});
test("finalization removes the pending child marker before clearing task state",async()=>{const pending={id:"pending",type:"heading_2",heading_2:{rich_text:[{plain_text:PENDING_PUBLICATION_MARKER}]}};const c=new FakeClient([{results:[pending]} ,{ok:true},{ok:true}]);await c.finalizePublication("page",DEFAULT_POLICY);assert.equal(c.calls[1].path,"/blocks/pending");assert.equal(c.calls[2].path,"/pages/page");});
test("failed repair keeps the pending marker so the next invocation remains repairable",async()=>{const pending={id:"pending",type:"heading_2",heading_2:{rich_text:[{plain_text:PENDING_PUBLICATION_MARKER}]}};const c=new FakeClient([{results:[{id:"page"}]},{results:[pending]},{results:[pending]},{ok:true},new PublicationError("provider/API failure while appending"),{results:[{id:"page"}]},{results:[pending]}]);const first=await c.findPublication("ds",DEFAULT_POLICY,"PLAN-X");assert.equal(first?.complete,false);await assert.rejects(c.repairIncomplete("page",buildPageBlocks(DEFAULT_POLICY,"plan")),/appending/);const second=await c.findPublication("ds",DEFAULT_POLICY,"PLAN-X");assert.deepEqual(second,{pageId:"page",url:undefined,complete:false});});
