import test from 'node:test';
import assert from 'node:assert/strict';
import { submit, wrapPrompt } from '../src/service.js';
import { ShotError } from '../src/errors.js';

class Store {
  created = 0; reads = 0; undeliveredFailures: string[] = [];
  constructor(readonly states: any[]) {}
  async createInvocation(_: string, id: string) { this.created++; return { id, pageId: 'page-1', state: 'pending', error: '' }; }
  async failUndeliveredInvocation(_: string, __: string, reason: string) { this.undeliveredFailures.push(reason); }
  async readInvocation(pageId: string, id: string) { return this.states[Math.min(this.reads++, this.states.length - 1)] ?? { pageId, id, state: 'pending', error: '' }; }
  async children() { return [{ type: 'paragraph', paragraph: { rich_text: [{ plain_text: 'Result' }] }, has_children: false }]; }
}
class DelayedStore extends Store {
  async readInvocation(pageId: string, id: string) { await new Promise(resolve => setTimeout(resolve, 15)); return super.readInvocation(pageId, id); }
}
class Browser {
  attempts = 0; opens = 0; inspections = 0; closes = 0; inspected: 'submitted'|'not_submitted'|'uncertain' = 'submitted'; authenticated = true; openError?: Error; fillError?: Error; submitError?: Error; inspectError?: Error;
  async withBrowser<T>(operation: () => Promise<T>) { return operation(); }
  async ensureAvailable() {} async ensureAuthenticated() { if (!this.authenticated) throw new ShotError('CHATGPT_AUTH_REQUIRED', 'required'); }
  async openFreshContext() { this.opens++; if (this.openError) throw this.openError; } async fillPrompt() { if (this.fillError) throw this.fillError; } async submitPrompt() { this.attempts++; if (this.submitError) throw this.submitError; } async inspectSubmission() { this.inspections++; if (this.inspectError) throw this.inspectError; return this.inspected; } async close() { this.closes++; }
}
const options = { acknowledgementMs: 0, executionMs: 25, pollMs: 1 };
test('completed invocation reads only completed page body', async () => { const result = await submit(new Store([{ state: 'completed', error: '' }]) as any, 'db', new Browser() as any, 'task', options); assert.equal(result, 'Result'); });
test('pending then in_progress never consumes Result before completed', async () => { const store = new Store([{ state: 'pending', error: '' }, { state: 'in_progress', error: '' }, { state: 'completed', error: '' }]); const result = await submit(store as any, 'db', new Browser() as any, 'task', { ...options, acknowledgementMs: 20 }); assert.equal(result, 'Result'); assert.equal(store.reads, 3); });
test('acknowledgment starts a full execution timeout window', async () => { const store = new DelayedStore([{ state: 'pending', error: '' }, { state: 'in_progress', error: '' }, { state: 'completed', error: '' }]); const result = await submit(store as any, 'db', new Browser() as any, 'task', { acknowledgementMs: 100, executionMs: 20, pollMs: 1 }); assert.equal(result, 'Result'); });
test('failed invocation reports Error and blank Error violates protocol', async () => { await assert.rejects(() => submit(new Store([{ state: 'failed', error: 'work failed' }]) as any, 'db', new Browser() as any, 'task', options), (e: any) => e.code === 'INVOCATION_FAILED'); await assert.rejects(() => submit(new Store([{ state: 'failed', error: '' }]) as any, 'db', new Browser() as any, 'task', options), (e: any) => e.code === 'INVALID_INVOCATION_STATE'); });
test('submitted inspection ends the expired acknowledgment window without a retry', async () => { const browser = new Browser(); browser.inspected = 'submitted'; await assert.rejects(() => submit(new Store([{ state: 'pending', error: '' }]) as any, 'db', browser as any, 'task', options), (e: any) => e.code === 'ACKNOWLEDGMENT_TIMEOUT'); assert.equal(browser.attempts, 1); assert.equal(browser.inspections, 1); });
test('uncertain inspection never retries', async () => { const browser = new Browser(); browser.inspected = 'uncertain'; await assert.rejects(() => submit(new Store([{ state: 'pending', error: '' }]) as any, 'db', browser as any, 'task', options), (e: any) => e.code === 'SUBMISSION_UNCERTAIN'); assert.equal(browser.attempts, 1); });
test('not submitted is retried once and terminalizes after the second confirmed non-delivery', async () => { const browser = new Browser(); browser.inspected = 'not_submitted'; const store = new Store([{ state: 'pending', error: '' }]); await assert.rejects(() => submit(store as any, 'db', browser as any, 'task', options), (e: any) => e.code === 'ACKNOWLEDGMENT_TIMEOUT'); assert.equal(browser.attempts, 2); assert.equal(browser.inspections, 2); assert.match(store.undeliveredFailures[0], /Second submission was not acknowledged/); });
test('acknowledged in-progress invocation never enters browser inspection', async () => { const browser = new Browser(); await assert.rejects(() => submit(new Store([{ state: 'in_progress', error: '' }]) as any, 'db', browser as any, 'task', options), (e: any) => e.code === 'EXECUTION_TIMEOUT'); assert.equal(browser.inspections, 0); });
test('authentication fails before pending invocation creation and releases its browser tab', async () => { const browser = new Browser(); browser.authenticated = false; const store = new Store([]); await assert.rejects(() => submit(store as any, 'db', browser as any, 'task', options), (e: any) => e.code === 'CHATGPT_AUTH_REQUIRED'); assert.equal(store.created, 0); assert.equal(browser.closes, 1); });
test('fresh context preflight fails before creating a pending invocation', async () => { const browser = new Browser(); browser.openError = new ShotError('BROWSER_UNAVAILABLE', 'fresh page unavailable'); const store = new Store([]); await assert.rejects(() => submit(store as any, 'db', browser as any, 'task', options), (e: any) => e.code === 'BROWSER_UNAVAILABLE'); assert.equal(store.created, 0); assert.equal(browser.opens, 1); });
test('fill failure terminalizes an undelivered pending invocation', async () => { const browser = new Browser(); browser.fillError = new ShotError('BROWSER_UNAVAILABLE', 'composer disappeared'); const store = new Store([]); await assert.rejects(() => submit(store as any, 'db', browser as any, 'task', options), (e: any) => e.code === 'BROWSER_UNAVAILABLE'); assert.equal(store.created, 1); assert.equal(browser.attempts, 0); assert.match(store.undeliveredFailures[0], /before prompt submission/); });
test('uncertain submit transport inspects before deciding whether to retry', async () => { const browser = new Browser(); browser.submitError = new ShotError('SUBMISSION_UNCERTAIN', 'transport lost'); browser.inspected = 'uncertain'; await assert.rejects(() => submit(new Store([]) as any, 'db', browser as any, 'task', options), (e: any) => e.code === 'SUBMISSION_UNCERTAIN'); assert.equal(browser.inspections, 1); assert.equal(browser.attempts, 1); });
test('acknowledgment inspection loss preserves submission uncertainty', async () => { const browser = new Browser(); browser.inspectError = new ShotError('BROWSER_UNAVAILABLE', 'page gone'); await assert.rejects(() => submit(new Store([{ state: 'pending', error: '' }]) as any, 'db', browser as any, 'task', options), (e: any) => e.code === 'SUBMISSION_UNCERTAIN'); assert.equal(browser.inspections, 1); assert.equal(browser.attempts, 1); });
test('wrapped prompt fixes Notion delivery protocol around caller task', () => { const prompt = wrapPrompt('caller task', 'inv-1', 'page-1'); assert.match(prompt, /caller task/); assert.match(prompt, /State/); assert.match(prompt, /Error/); assert.match(prompt, /inv-1/); });
